FROM timhughes/centos:centos7
RUN yum -y install \
	curl \
	gcc \
	gcc-c++ \
	libyaml-devel \
	make \
	openssl-devel \
	patch \
	readline-devel \
	zlib-devel \
    autoconf \
    automake \
    bzip2 \
    bzip2-devel \
    file \
    gcc \
    gcc-c++ \
    git \
    hostname \
    ncurses-devel  \
    patch \
    readline-devel  \
    sqlite-devel \
    tar

RUN	yum clean all

