FROM timhughes/centos:centos7
RUN yum -y install \
    autoconf \
    automake \
    bzip2 \
    bzip2-devel \
    curl \
    file \
    gcc \
    gcc-c++ \
    git \
    hostname \
    libyaml-devel \
    make \
    ncurses-devel \
    openssl-devel \
    patch \
    readline-devel \
    sqlite-devel \
    tar \
    zlib-devel

RUN yum clean all
