FROM timhughes/centos:centos7_buildpack-deps
RUN curl -L
https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
RUN  pyenv install 2.6.9
RUN  pyenv install 2.7.11
RUN  pyenv install 3.5.1
